name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: python -m unittest discover

      - name: Build executable
        run: python -O build.py

      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: imdupes-artifacts
          path: |
            dist/imdupes-v*.zip
            dist/imdupes-v*.tar

      - name: Archive checksum file
        uses: actions/upload-artifact@v3
        with:
          name: imdupes-checksums
          path: dist/imdupes-v*.sha256
